# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: imu.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'imu.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\timu.proto\x12\x07sensors\"w\n\x07IMUData\x12\n\n\x02\x61x\x18\x01 \x01(\x02\x12\n\n\x02\x61y\x18\x02 \x01(\x02\x12\n\n\x02\x61z\x18\x03 \x01(\x02\x12\n\n\x02gx\x18\x04 \x01(\x02\x12\n\n\x02gy\x18\x05 \x01(\x02\x12\n\n\x02gz\x18\x06 \x01(\x02\x12\x16\n\ttimestamp\x18\x07 \x01(\x04H\x00\x88\x01\x01\x42\x0c\n\n_timestamp\"\x12\n\x10ImuStreamRequest2I\n\nImuService\x12;\n\ngetImuData\x12\x19.sensors.ImuStreamRequest\x1a\x10.sensors.IMUData0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'imu_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMUDATA']._serialized_start=22
  _globals['_IMUDATA']._serialized_end=141
  _globals['_IMUSTREAMREQUEST']._serialized_start=143
  _globals['_IMUSTREAMREQUEST']._serialized_end=161
  _globals['_IMUSERVICE']._serialized_start=163
  _globals['_IMUSERVICE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
