# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: recording.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'recording.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import lidar_pb2 as lidar__pb2
from . import imu_pb2 as imu__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0frecording.proto\x12\x07sensors\x1a\x0blidar.proto\x1a\timu.proto\"`\n\x0eRecordingEntry\x12$\n\x04scan\x18\x01 \x01(\x0b\x32\x14.sensors.PointCloud3H\x00\x12\x1f\n\x03imu\x18\x02 \x01(\x0b\x32\x10.sensors.IMUDataH\x00\x42\x07\n\x05\x65ntry\"5\n\x0fsaveFileRequest\x12\x15\n\x08\x66ilename\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x0b\n\t_filenameb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'recording_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECORDINGENTRY']._serialized_start=52
  _globals['_RECORDINGENTRY']._serialized_end=148
  _globals['_SAVEFILEREQUEST']._serialized_start=150
  _globals['_SAVEFILEREQUEST']._serialized_end=203
# @@protoc_insertion_point(module_scope)
