syntax = "proto3";

import "header.proto";

package sensors;

message PointCloud3 { 
    Header header = 1;
    repeated float x = 2 [packed=true];
    repeated float y = 3 [packed=true];
    repeated float z = 4 [packed=true];

    repeated uint32 intensity = 5 [packed=true];

    // Optional color information
    repeated float r = 6 [packed=true];
    repeated float g = 7 [packed=true];
    repeated float b = 8 [packed=true];

}

message LidarStreamRequest {
}

message SubSampledLidarStreamRequest {
        float voxel_size = 1;
}

service LidarService {
    rpc getLidarScan(LidarStreamRequest) returns (stream PointCloud3);
    rpc getSubSampledLidarScan(stream SubSampledLidarStreamRequest) returns (stream PointCloud3);
}
